{{- /*
This ConfigMap contains the full Patroni configuration - excluding the credentials for users.
*/ -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "timescaledb.fullname" . }}-patroni
  labels:
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster-name: {{ template "clusterName" . }}
data:
  patroni: |
{{ if not .Values.backup.enable -}}
{{- /*
If no backup is configured, archive_command will fail. A failing archive_command on a cluster
is going to cause WAL to be kept around forever, meaning we'll fill up Volumes we have quite quickly.

Therefore, if the backup is disabled, we switch the archive_command to the always succeeding /bin/true command
*/ -}}
{{- $_ := set .Values "patroni" (merge (dict "postgresql" (dict "parameters" (dict "archive_command" "/bin/true"))) .Values.patroni) }}
{{- end -}}
{{ .Values.patroni | toYaml | indent 4 }}
...
