---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "timescaledb.fullname" . }}-passwords
  labels:
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $val := .Values.credentials }}
  {{ $key | quote }}: {{ $val | default "" | b64enc }}
{{- end }}
...
