# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.
{{- if eq .Values.secrets.pgbackrestSecretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secrets_pgbackrest" $ }}
  labels:
    app: {{ template "timescaledb.fullname" $ }}
    cluster-name: {{ template "clusterName" $ }}
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/resource-policy": keep
type: Opaque
{{- if .Release.IsUpgrade }}
data: {{ (lookup "v1" "Secret" .Release.Namespace (include "secrets_pgbackrest" .)).data }}
{{- else }}
stringData:
{{ toYaml .Values.secrets.pgbackrest | indent 2 }}
{{- end }}
...
{{- end }}
