# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.
{{- if eq .Values.secrets.credentialsSecretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secrets_credentials" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "timescaledb-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: patroni
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/resource-policy": keep
type: Opaque
{{- if .Release.IsUpgrade }}
data: {{ (lookup "v1" "Secret" .Release.Namespace (include "secrets_credentials" .)).data }}
{{ else }}
stringData:
  PATRONI_SUPERUSER_PASSWORD: {{ default (randAlphaNum 16) .Values.secrets.credentials.PATRONI_SUPERUSER_PASSWORD | quote }}
  PATRONI_REPLICATION_PASSWORD: {{ default (randAlphaNum 16) .Values.secrets.credentials.PATRONI_REPLICATION_PASSWORD | quote }}
  PATRONI_admin_PASSWORD: {{ default (randAlphaNum 16) .Values.secrets.credentials.PATRONI_admin_PASSWORD | quote }}
  {{- range $k, $v := .Values.secrets.credentials }}
    {{- $passwords := list "PATRONI_SUPERUSER_PASSWORD" "PATRONI_REPLICATION_PASSWORD" "PATRONI_admin_PASSWORD" }}
    {{- if not (has $k $passwords) }}
      {{- $k | nindent 2 }}: {{ $v }}
    {{- end }}
  {{- end }}
{{- end }}
...
{{- end }}
