# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.

{{- if (.Values.unsafe | default false) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "secrets_credentials" $ }}"
  labels:
    app: {{ template "timescaledb.fullname" . }}
    cluster-name: {{ template "clusterName" . }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
{{- if .Release.IsUpgrade }}
  PATRONI_SUPERUSER_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.secretNames.credentials).data "PATRONI_SUPERUSER_PASSWORD" }}
  PATRONI_REPLICATION_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.secretNames.credentials).data "PATRONI_REPLICATION_PASSWORD" }}
  PATRONI_admin_PASSWORD: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.secretNames.credentials).data "PATRONI_admin_PASSWORD" }}
{{ else }}
  PATRONI_SUPERUSER_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  PATRONI_REPLICATION_PASSWORD: {{ randAlphaNum 16 | b64enc }}
  PATRONI_admin_PASSWORD: {{ randAlphaNum 16 | b64enc }}
{{ end }}
...
---
{{ $ca := genCA (include "clusterName" .) 1826 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "secrets_certificate" $ }}
  labels:
    app: {{ template "timescaledb.fullname" $ }}
    cluster-name: {{ template "clusterName" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: kubernetes.io/tls
data:
{{- if .Release.IsUpgrade }}
  tls.crt: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.secretNames.certificate).data "tls.crt" }}
  tls.key: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.secretNames.certificate).data "tls.key" }}
{{ else }}
  tls.crt: {{ $ca.Cert | b64enc }}
  tls.key: {{ $ca.Key  | b64enc }}
{{ end }}
...
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "secrets_pgbackrest" $ }}"
  labels:
    app: {{ template "timescaledb.fullname" $ }}
    cluster-name: {{ template "clusterName" $ }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
{{- if .Release.IsUpgrade }}
  PGBACKREST_REPO1_S3_REGION: {{ index (lookup "v1" "Secret" .Release.Namespace .Values.secretNames.pgbackrest).data "PGBACKREST_REPO1_S3_REGION" }}
{{ else }}
  PGBACKREST_REPO1_S3_REGION: {{ randAlphaNum 16 | b64enc }}
{{ end }}
...
{{- end }}
