apiVersion: v1
kind: Secret
metadata:
  name: {{ template "timescaledb.fullname" . }}
  labels:
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password-superuser: {{ .Values.credentials.superuser | b64enc }}
  password-admin: {{ .Values.credentials.admin | b64enc }}
  password-standby: {{ .Values.credentials.standby | b64enc }}
