---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "timescaledb.fullname" . }}
  labels:
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
spec:
  type: LoadBalancer
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
  selector:
    app: {{ template "timescaledb.fullname" . }}
    timescaleNodeType: access
...
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "timescaledb.fullname" . }}-data
  labels:
    app: {{ template "timescaledb.fullname" . }}
    chart: {{ template "timescaledb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
  selector:
    app: {{ template "timescaledb.fullname" . }}
    timescaleNodeType: data
...