name: "Helm Lint"
on:
- push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Copy example values files to the expected Helm Linter locations
        run: make refresh-ci-values

      - name: Run linter on Helm Charts
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint

      - name: Install shellcheck
        run: sudo apt-get install shellcheck

      - name: Run shellcheck on all scripts
        run: make shellcheck
